# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: garbage_and_dumpsters_data.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'garbage_and_dumpsters_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n garbage_and_dumpsters_data.proto\x12\x1agarbage_and_dumpsters_data\"\xa9\x01\n\x17\x44umpstersAndGarbageData\x12\x15\n\rcount_of_full\x18\x01 \x01(\x05\x12\x16\n\x0e\x63ount_of_empty\x18\x02 \x01(\x05\x12\x17\n\x0f\x63ount_of_closed\x18\x03 \x01(\x05\x12\x1b\n\x13small_garbage_level\x18\x04 \x01(\x05\x12\x1b\n\x13large_garbage_level\x18\x05 \x01(\x05\x12\x0c\n\x04time\x18\x06 \x01(\x05\"f\n\x0e\x44umpstersCount\x12\x15\n\rcount_of_full\x18\x01 \x01(\x05\x12\x16\n\x0e\x63ount_of_empty\x18\x02 \x01(\x05\x12\x17\n\x0f\x63ount_of_closed\x18\x03 \x01(\x05\x12\x0c\n\x04time\x18\x04 \x01(\x05\"V\n\x0cGarbageLevel\x12\x1b\n\x13small_garbage_level\x18\x01 \x01(\x05\x12\x1b\n\x13large_garbage_level\x18\x02 \x01(\x05\x12\x0c\n\x04time\x18\x03 \x01(\x05\"\x14\n\x04Time\x12\x0c\n\x04time\x18\x01 \x01(\x05\x32\x8d\x01\n\x1a\x44umpstersAndGarbageService\x12o\n\x16GetDumpstersAndGarbage\x12 .garbage_and_dumpsters_data.Time\x1a\x33.garbage_and_dumpsters_data.DumpstersAndGarbageData2u\n\x10\x44umpstersService\x12\x61\n\x11GetDumpstersCount\x12 .garbage_and_dumpsters_data.Time\x1a*.garbage_and_dumpsters_data.DumpstersCount2o\n\x0eGarbageService\x12]\n\x0fGetGarbageLevel\x12 .garbage_and_dumpsters_data.Time\x1a(.garbage_and_dumpsters_data.GarbageLevelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'garbage_and_dumpsters_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DUMPSTERSANDGARBAGEDATA']._serialized_start=65
  _globals['_DUMPSTERSANDGARBAGEDATA']._serialized_end=234
  _globals['_DUMPSTERSCOUNT']._serialized_start=236
  _globals['_DUMPSTERSCOUNT']._serialized_end=338
  _globals['_GARBAGELEVEL']._serialized_start=340
  _globals['_GARBAGELEVEL']._serialized_end=426
  _globals['_TIME']._serialized_start=428
  _globals['_TIME']._serialized_end=448
  _globals['_DUMPSTERSANDGARBAGESERVICE']._serialized_start=451
  _globals['_DUMPSTERSANDGARBAGESERVICE']._serialized_end=592
  _globals['_DUMPSTERSSERVICE']._serialized_start=594
  _globals['_DUMPSTERSSERVICE']._serialized_end=711
  _globals['_GARBAGESERVICE']._serialized_start=713
  _globals['_GARBAGESERVICE']._serialized_end=824
# @@protoc_insertion_point(module_scope)
