# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: garbage_and_dumpsters_data.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'garbage_and_dumpsters_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n garbage_and_dumpsters_data.proto\x12\x1agarbage_and_dumpsters_data\"X\n\x0e\x44umpstersCount\x12\x15\n\rcount_of_full\x18\x01 \x01(\x05\x12\x16\n\x0e\x63ount_of_empty\x18\x02 \x01(\x05\x12\x17\n\x0f\x63ount_of_closed\x18\x03 \x01(\x05\"0\n\x11SmallGarbageLevel\x12\x1b\n\x13small_garbage_level\x18\x01 \x01(\x05\"0\n\x11LargeGarbageLevel\x12\x1b\n\x13large_garbage_level\x18\x01 \x01(\x05\"\x14\n\x04Time\x12\x0c\n\x04time\x18\x01 \x01(\x05\x32u\n\x10\x44umpstersService\x12\x61\n\x11GetDumpstersCount\x12 .garbage_and_dumpsters_data.Time\x1a*.garbage_and_dumpsters_data.DumpstersCount2~\n\x13SmallGarbageService\x12g\n\x14GetSmallGarbageLevel\x12 .garbage_and_dumpsters_data.Time\x1a-.garbage_and_dumpsters_data.SmallGarbageLevel2~\n\x13LargeGarbageService\x12g\n\x14GetLargeGarbageLevel\x12 .garbage_and_dumpsters_data.Time\x1a-.garbage_and_dumpsters_data.LargeGarbageLevelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'garbage_and_dumpsters_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DUMPSTERSCOUNT']._serialized_start=64
  _globals['_DUMPSTERSCOUNT']._serialized_end=152
  _globals['_SMALLGARBAGELEVEL']._serialized_start=154
  _globals['_SMALLGARBAGELEVEL']._serialized_end=202
  _globals['_LARGEGARBAGELEVEL']._serialized_start=204
  _globals['_LARGEGARBAGELEVEL']._serialized_end=252
  _globals['_TIME']._serialized_start=254
  _globals['_TIME']._serialized_end=274
  _globals['_DUMPSTERSSERVICE']._serialized_start=276
  _globals['_DUMPSTERSSERVICE']._serialized_end=393
  _globals['_SMALLGARBAGESERVICE']._serialized_start=395
  _globals['_SMALLGARBAGESERVICE']._serialized_end=521
  _globals['_LARGEGARBAGESERVICE']._serialized_start=523
  _globals['_LARGEGARBAGESERVICE']._serialized_end=649
# @@protoc_insertion_point(module_scope)
