# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import garbage_and_dumpsters_data_pb2 as garbage__and__dumpsters__data__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in garbage_and_dumpsters_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DumpstersAndGarbageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDumpstersAndGarbage = channel.unary_unary(
                '/garbage_and_dumpsters_data.DumpstersAndGarbageService/GetDumpstersAndGarbage',
                request_serializer=garbage__and__dumpsters__data__pb2.Time.SerializeToString,
                response_deserializer=garbage__and__dumpsters__data__pb2.DumpstersAndGarbageData.FromString,
                _registered_method=True)


class DumpstersAndGarbageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDumpstersAndGarbage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DumpstersAndGarbageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDumpstersAndGarbage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDumpstersAndGarbage,
                    request_deserializer=garbage__and__dumpsters__data__pb2.Time.FromString,
                    response_serializer=garbage__and__dumpsters__data__pb2.DumpstersAndGarbageData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'garbage_and_dumpsters_data.DumpstersAndGarbageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('garbage_and_dumpsters_data.DumpstersAndGarbageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DumpstersAndGarbageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDumpstersAndGarbage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garbage_and_dumpsters_data.DumpstersAndGarbageService/GetDumpstersAndGarbage',
            garbage__and__dumpsters__data__pb2.Time.SerializeToString,
            garbage__and__dumpsters__data__pb2.DumpstersAndGarbageData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DumpstersServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDumpstersCount = channel.unary_unary(
                '/garbage_and_dumpsters_data.DumpstersService/GetDumpstersCount',
                request_serializer=garbage__and__dumpsters__data__pb2.Time.SerializeToString,
                response_deserializer=garbage__and__dumpsters__data__pb2.DumpstersCount.FromString,
                _registered_method=True)


class DumpstersServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDumpstersCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DumpstersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDumpstersCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDumpstersCount,
                    request_deserializer=garbage__and__dumpsters__data__pb2.Time.FromString,
                    response_serializer=garbage__and__dumpsters__data__pb2.DumpstersCount.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'garbage_and_dumpsters_data.DumpstersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('garbage_and_dumpsters_data.DumpstersService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DumpstersService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDumpstersCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garbage_and_dumpsters_data.DumpstersService/GetDumpstersCount',
            garbage__and__dumpsters__data__pb2.Time.SerializeToString,
            garbage__and__dumpsters__data__pb2.DumpstersCount.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GarbageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGarbageLevel = channel.unary_unary(
                '/garbage_and_dumpsters_data.GarbageService/GetGarbageLevel',
                request_serializer=garbage__and__dumpsters__data__pb2.Time.SerializeToString,
                response_deserializer=garbage__and__dumpsters__data__pb2.GarbageLevel.FromString,
                _registered_method=True)


class GarbageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGarbageLevel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GarbageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGarbageLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGarbageLevel,
                    request_deserializer=garbage__and__dumpsters__data__pb2.Time.FromString,
                    response_serializer=garbage__and__dumpsters__data__pb2.GarbageLevel.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'garbage_and_dumpsters_data.GarbageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('garbage_and_dumpsters_data.GarbageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GarbageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGarbageLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/garbage_and_dumpsters_data.GarbageService/GetGarbageLevel',
            garbage__and__dumpsters__data__pb2.Time.SerializeToString,
            garbage__and__dumpsters__data__pb2.GarbageLevel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
